### ISSUE TITLE
How to run on linux?

### ISSUE THREAD

**Issue by trinitysenpai** [drknzz/auto-lingo#11]
Hello, I'm trying to get this to run on my linux machine.

```
Traceback (most recent call last):
  File "/home/****/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/****/Documents/Programming/python/auto-lingo/auto-lingo.py", line 796, in <module>
    main()
  File "/home/****/Documents/Programming/python/auto-lingo/auto-lingo.py", line 773, in main
    driver = webdriver.Chrome(settings['chromedriver_path'], options=chrome_options)
  File "/home/****/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/****/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'C:\Program Files (x86)\chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

😄 Much thanks!

**Comment by drknzz** [comment]
Hey,
have you tried replacing the path in [settings.json](https://github.com/drknzz/auto-lingo/blob/main/settings.json) to point to the location of chromedriver?

**Comment by trinitysenpai** [comment]
> Hey, have you tried replacing the path in [settings.json](https://github.com/drknzz/auto-lingo/blob/main/settings.json) to point to the location of chromedriver?

Thanks🙏 , I was using `/usr/local/bin/chromedriver` instead of `/usr/bin/chromedriver`
