### ISSUE TITLE
Issues bot in Learn Mode

### ISSUE THREAD

**Issue by gorouflex** [drknzz/auto-lingo#12]
The bot doesn't work in Learn mode, I'm using bot to earn German lesson xp. Help me!
P/S: Bot still works with story mode
![image](https://user-images.githubusercontent.com/98001973/150056928-4ece2cd6-4649-40e1-9fe1-e96e882cf7e7.png)

**Comment by gorouflex** [comment]
Help me please?

**Comment by gorouflex** [comment]
Ok thanks you

**Comment by gorouflex** [comment]
Oh nevermind LEARN MODE still didn't work

**Comment by Findarato** [comment]
oh sorry. It should have resolved the errors about the deprecated messages.  Is there any new errors?

**Comment by dsakura** [comment]
Problem here too, and here is stuck in one lesson, without advancing, which I have already completed. Before completing the lesson the bot just applied automatic "enter".
`C:\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py:341: UserWarning: find_element_by_tag_name is deprecated. Please use find_element(by=By.TAG_NAME, value=name) instead
  warnings.warn("find_element_by_tag_name is deprecated. Please use find_element(by=By.TAG_NAME, value=name) instead")
Traceback (most recent call last):
  File "H:\auto-lingo-main\auto-lingo.py", line 911, in <module>
    main()
  File "H:\auto-lingo-main\auto-lingo.py", line 903, in main
    learn_bot()
  File "H:\auto-lingo-main\auto-lingo.py", line 852, in learn_bot
    complete_skill(possible_skip_to_lesson)
  File "H:\auto-lingo-main\auto-lingo.py", line 732, in complete_skill
    time.sleep(1)`

Thank you

**Comment by NicholasUchoa** [comment]
I'm having problems with learn as well. This is what appears in the chrome console.
The error keep going
![lessons-error](https://user-images.githubusercontent.com/39327656/191384169-6517b6b9-3d0e-440d-8bb0-480c5050fcc2.jpg)

This is what appears in the cmd window
C:\Users\Dulce\Downloads\Duolingo-hack\auto-lingo-main>python auto-lingo.py -l -a
🏁 Starting out

DevTools listening on ws://127.0.0.1:52174/devtools/browser/3de8fb79-bce4-4f6e-8a2b-e132a20cdf1b
Traceback (most recent call last):
  File "C:\Users\Dulce\Downloads\Duolingo-hack\auto-lingo-main\auto-lingo.py", line 911, in <module>
    main()
  File "C:\Users\Dulce\Downloads\Duolingo-hack\auto-lingo-main\auto-lingo.py", line 900, in main
    log_in(login, password)
  File "C:\Users\Dulce\Downloads\Duolingo-hack\auto-lingo-main\auto-lingo.py", line 132, in log_in
    login_button.click()
  File "C:\Users\Dulce\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 88, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Dulce\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 396, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Dulce\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Dulce\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button class="_1rl91 _3HhhB _2NolF _275sd _1ZefG _2oW4v" data-test="register-button" type="submit">...</button> is not clickable at point (674, 328). Other element would receive the click: <div class="_3wkBv">...</div>
  (Session info: chrome=105.0.5195.127)
Stacktrace:
Backtrace:
