### ISSUE TITLE
Learn Mode

### ISSUE THREAD

**Issue by dan1ck** [drknzz/auto-lingo#25]
Just tried installing and running the bot which all worked fine but if I choose the Learn Mode it opens the right page but cannot start a module and just returns a TimeoutException after a while.
Is there any way to get this updated and working again?

**Comment by Windanze** [comment]
I am finding the same is true. Cannot use learn mode. I get the same timeoutexceptions as above. I started in -a -l and it logs in, stays on learning page and then times out.
________________________________________________________________________________________________________________________
DevTools listening on ws://127.0.0.1:63085/devtools/browser/d927bade-a895-47ac-ab26-95dc132392b0
Loggin in
Traceback (most recent call last):
File "C:\Users\XXXX\autoLING\auto-lingo\auto-lingo.py", line 911, in
main()
File "C:\Users\XXXX\autoLING\auto-lingo\auto-lingo.py", line 903, in main
learn_bot()
File "C:\Users\XXXX\autoLING\auto-lingo\auto-lingo.py", line 778, in learn_bot
skills = WebDriverWait(driver, 20).until(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
________________________________________________________________________________________________________________________
Thanks for the work.

**Comment by AlinaRinn** [comment]
Same error

![image](https://user-images.githubusercontent.com/64281268/202553878-b576270e-f65d-49b7-b7bc-d3ad7d006866.png)

**Comment by dan1ck** [comment]
@drknzz: Any chance you will pick this up again?

**Comment by drknzz** [comment]
Hey @dan1ck,
I'm quite busy atm but I might be able to find time soon to address the piled up issues about learn mode as well as do an overall update so it works better than ever. Maybe even some GUI for overall better UX? 👀

**Comment by dan1ck** [comment]
Cool, thank you for the feedback @drknzz!
No pressure at all but would be cool if you find some time to update :)

**Comment by trfi** [comment]
I 

> Hey @dan1ck, I'm quite busy atm but I might be able to find time soon to address the piled up issues about learn mode as well as do an overall update so it works better than ever. Maybe even some GUI for overall better UX? 👀

I'm looking forward to it. Thank you so much

**Comment by Ayasato69** [comment]
> Same error
> 
> ![image](https://user-images.githubusercontent.com/64281268/202553878-b576270e-f65d-49b7-b7bc-d3ad7d006866.png)

same is happening to me
