### ISSUE TITLE
Getting traceback error after logging in

### ISSUE THREAD

**Issue by TomerGamerTV** [drknzz/auto-lingo#29]
After i login nothing happens and after a few seconds it throws this error:
```
Loggin in
Traceback (most recent call last):
  File "D:\Local Downloads\auto-lingo\auto-lingo.py", line 911, in <module>
    main()
  File "D:\Local Downloads\auto-lingo\auto-lingo.py", line 903, in main
    learn_bot()
  File "D:\Local Downloads\auto-lingo\auto-lingo.py", line 778, in learn_bot
    skills = WebDriverWait(driver, 20).until(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by avyaymc** [comment]
Yep, same issue. Any fix?

**Comment by Ariuuwu** [comment]
same.. @drknzz any fix please..?

**Comment by AlinaRinn** [comment]
@avyaymc @Ariuuwu @TomerGamerTV As I understand it, this error is due to the fact that duolingo changed names of div-containers on site, so we need to select div-names again

**Comment by L1LHomie** [comment]
@AlinaRinn I don't understand your proposed solution, can you explain more?

**Comment by GentNisjes** [comment]
@L1LHomie When duolingo changes/updates (i.e. adding new buttons / text / animations) the layout of their web version, the identifiers of existing buttons/texts might change. Since Selenium projects are relying on these identifiers to find where to click, there is this "risk" of having to update the identifiers of the buttons you want to click on (or the ids of whatever you want to access through selenium).
In other words someone has to go through the code and check if the identifiers used still correspond to the intended buttons or text fields. Ideally this would be done by the creator of the code since debugging this type of stuff can be quite an unpleasant task if you dont know what you're exactly looking for. 

@AlinaRinn have you found a working solution for the updated duolingo site?
@drknzz are you still updating the project?
